# Dependencies
markdown         : redcarpet
pygments         : true

# Permalinks
permalink        : pretty

# Site settings
title            : The Blog of a Nomad
description      : Yet Another Blog On Tech
url              : dominicwong617.github.io
baseurl          : /
tagline          : A Jekyll theme

author           :
  name           : Dominic Wong
  url            : https://twitter.com/dominicwong617

# Build settings
markdown         : kramdown
permalink        : pretty

paginate         : 5

